### ISSUE TITLE
optional priorityClasses for score / mcore jobs

### ISSUE THREAD

**Issue by rptaylor** [HSF/harvester#118]
Hi @fbarreir many thanks for the memory and disk related improvements!

Following up from the " CA-VICTORIA-K8S-T2 MCORE " email, I suggest enabling PriorityClasses for Harvester jobs.
It is just a string in the pod spec of the job:
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority

We could have e.g. `k8s.scheduling.priorityclass.score` and `k8s.scheduling.priorityclass.mcore`.  If a string is defined in CRIC for one of those parameters, it is used as the priorityClassName in the pod spec of the job, otherwise priorityClassName is omitted.

At least this could allow us to start testing an elevated priority for mcore to see if is a suitable solution.

**Comment by fbarreir** [comment]
hi @rptaylor,

In principle it's implemented, but for testing it would help me if you can define a priorityClass in your TEST cluster. Is that possible?

The CRIC parameters will be:
```
k8s.scheduler.priorityClassName.score
k8s.scheduler.priorityClassName.score_himem
k8s.scheduler.priorityClassName.mcore
k8s.scheduler.priorityClassName.mcore_himem
```

Regards,
Fernando

**Comment by rptaylor** [comment]
Hi @fbarreir , certainly, I made a priorityClass called `uber-user-low`  on the dev cluster.  Thanks! I'll test it.

**Comment by fbarreir** [comment]
Thanks @rptaylor . I deployed the code changes and seems OK to me.

- a MCORE worker with priority class
```
[harvester]# kubectl describe pods grid-job-9305688-zt9cz
Name:                 grid-job-9305688-zt9cz
Namespace:            harvester
Priority:             500
Priority Class Name:  uber-user-significant
Node: ...
```
- a SCORE worker without priority class
```
[harvester]# kubectl describe pods grid-job-9305686-vrvcx
Name:         grid-job-9305686-vrvcx
Namespace:    harvester
Priority:     0
Node:  ...
```

Let me know if you need any adjustment.
