### ISSUE TITLE
Implement minNewWorkersPerCycle?

### ISSUE THREAD

**Issue by nikmagini** [HSF/harvester#27]
From Peter Love:
"we need to have a continuous stream (1/cycle) submitted regardless of how much work is in panda. This avoids the problem we see now where no workers are submitted for whatever reason."

Implement a setting to force submission of a min number of new workers per cycle, regardless of assigned work.
Keep default at 0; to be set for special queues used to test pilots.

Is this feasible?
Cheers
N

**Comment by ptrlv** [comment]
Just to add that this will be used in an ad-hoc way on the devel harvester, maybe one day per month. It helps remove WMS lag when we deploy new wrappers.

**Comment by susanka068** [comment]
if No one working on this issue right now I'd like to work on it !

**Comment by fbarreir** [comment]
We solved it by changing the configuration
