### ISSUE TITLE
Bug when checking missing attributes

### ISSUE THREAD

**Issue by chnzhangrui** [HSF/harvester#28]
https://github.com/HSF/harvester/blob/f9469f25834ac44d1f58f8f119e9b7af0134db63/pandaharvester/harvestercore/queue_config_mapper.py#L533

The condition will always happen. Better to check the length.
`if len(missing_attr_list) != 0:`

**Comment by tmaeno** [comment]
missing_attr_list is a list. For lists,

`if a_list:`

is equivalent to

`if len(a_list) != 0:`

and PEP8 even recommends the former

https://www.python.org/dev/peps/pep-0008/#programming-recommendations

although I'm not a huge fan of this syntax.

**Comment by chnzhangrui** [comment]
I think you are right. Thanks!
