### ISSUE TITLE
Job fetcher does not pick up new queues correctly

### ISSUE THREAD

**Issue by davidgcameron** [HSF/harvester#53]
I was trying to figure out why new unified queues in push mode are never picked up correctly. The prodSourceLabel is always set to "managed" when it should be "unified". Harvester has to be manually restarted every time a new queue is added to make it use the correct label.

I think it's because the panda queue info used by the JobFetcher is never refreshed. This means the check for grand unified state of a queue which was created after harvester started always returns false here: https://github.com/HSF/harvester/blob/master/pandaharvester/harvesterbody/job_fetcher.py#L55

So the solution would be to update the queue info periodically.

**Comment by fbarreir** [comment]
Fixed in https://github.com/HSF/harvester/commit/15fe8d90757fb55461e3afe492bbad2c177a7c69
