### ISSUE TITLE
Does 4th quote is a necessary one?

### ISSUE THREAD

**Issue by virthead** [HSF/harvester#7]
https://github.com/HSF/harvester/blob/e96c4fac1d27d56594e7cb82275d703fdc9b3418/pandaharvester/harvestercore/core_utils.py#L280

**Comment by virthead** [comment]
With the 4th quote pool data catalog has the following formatting:
"<File ID="6ed5639e-3342-40fb-abb6-02b54a117ec8">
        <logical>
        <lfn name="dy2018P03_testFE.284990-11153-0.stdout.gz"/>
        </logical>
        <metadata att_name="fsize" att_value = "13703"/>
        <metadata att_name="adler32" att_value="1d1befc5"/>
        </File> "<File ID="9e22afaf-ce44-4503-b215-2cada3449764">
        <logical>
        <lfn name="dy2018P03_testFE.284990-11153-0.stderr.gz"/>
        </logical>
        <metadata att_name="fsize" att_value = "2789"/>
        <metadata att_name="adler32" att_value="998780b9"/>
        </File> "<File ID="7ae04436-64e3-4fee-856d-ce8b31f07309">

**Comment by tmaeno** [comment]
fixed in the repo.
