### ISSUE TITLE
Are there plans to implement this function?

### ISSUE THREAD

**Issue by virthead** [HSF/harvester#9]
https://github.com/HSF/harvester/blob/34fc5bb796655bd28d719e5dc88a88f5bdbdbe25/pandaharvester/harvestermisc/htcondor_utils.py#L833

I'm falling into not implemented exception quite often.

**Comment by mightqxc** [comment]
@virthead 
Can you install "htcondor" in your python venv (e.g. pip install htcondor)?
After installing it one will not hit this exception.

This function uses condor command which is less efficient than htcondor python client. Without strong need the implementation is postponed.

**Comment by virthead** [comment]
I see, thanks for the hint, have just installed it.
