### ISSUE TITLE
check_credential_lifetime not in ArcproxyCredManager

### ISSUE THREAD

**Issue by rodwalker** [HSF/harvester#94]
I see the method in no_voms_cred_manager.py and base_cred_manager.py

    lifetime = exeCore.check_credential_lifetime()
AttributeError: 'ArcproxyCredManager' object has no attribute 'check_credential_lifetime'

Cheers,
Rod.

**Comment by fbarreir** [comment]
It's optional in case the credential manager plugin wants to monitor the lifetime of the proxy. If the method is not implemented, the message you quoted will be logged, but everything else will work normally.

**Comment by rodwalker** [comment]
Ok. Things get a bit confused when the plain proxy expires. The pilot proxy
is expired but the 'valid' test says it is ok
> arcproxy -i vomsACvalidityLeft -P proxy/pilot
281583
> arcproxy -i validityLeft -P proxy/pilot
0

It is like the vom validity can exceed the non-voms validity.

Deleting the voms proxies helps, but then I think they are recreated every
hour rather than every 5mins (validity check). A restart fixes that of
course.
Not a big deal - I should not let the plain proxy expire.

Cheers,
Rod.

**Comment by mightqxc** [comment]
Fixed in #96
